## YAML Template.
---
#installation d'Apache sur le serveur de développement
- name: Installation d'Apache
  hosts: all  
  tasks:
    - name: Inscrire le nouveau dépôt
      apt_repository:
       repo: deb http://ftp.fr.debian.org/debian/ stretch main
       state: present
       update_cache: yes
    - name: Installation d'apache2
      apt:
       name: apache2,ca-certificates,apt-transport-https
       state: present
    #- name: Démarrer le service Apache
     # service:  
      #  name: apache2   
       # state: started
        #enabled: yes 
#Installation de php7   
    - name: Enregistrer une clé  
      apt_key:  
       url: https://packages.sury.org/php/apt.gpg  
       state: present 
    - name: Inscrire le nouveau dépôt
      apt_repository:
        repo: deb https://packages.sury.org/php/ stretch main
        state: present
        update_cache: yes
    - name: Installation de php7
      apt:
       name: php7.2
       state: present 
    - name: Redémarrer apache
      service:
       name: apache2
       state: started
       enabled: yes
       
- name: Installation de Mysql
  hosts: all  tasks
  tasks:
    - name: Installer python-pip
      apt:
       name: python-pip
       state: present
    - name: Installer le module Python pour Mysql
      pip:
       name: PyMySQL 
    - name: Installation python-mysqldb
      apt:
       name: python-mysqldb
       state: present
    - name: Installation mysql server
      apt:
       name: mysql-server
       state: present
    - name: Gestion du my.cnf
      copy:
       src: /var/www/autres/my.cnf.j2
       dest: /root/.my.cnf   
       owner: root 
       group: root  
       mode: 0600      
    - name: Redémarrer MySQL
      service:
       name: mysql
       state: started
       enabled: yes
    - name: Gestion du mot de passe du root
      mysql_user:
       name: root
       password: abc123 
       login_unix_socket: /var/run/mysqld/mysqld.sock
    - name: Création d'une base de données 
      mysql_db:     
       name: "{{mysql_db}}" 
       #{{mysql_db]] correspond à la variable de machine-dev.inv
       state: present   
       login_unix_socket: /var/run/mysqld/mysqld.sock 
    - name: Création de l'utilisateur eleve et affectation des privilèges sur une base de données 
      mysql_user:
       name: "{{mysql_user}}"
       password: "{{mysql_password}}" 
       host: localhost 
       priv: "{{mysql_db}}.*:ALL,GRANT"   
       login_unix_socket: /var/run/mysqld/mysqld.sock
       